parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: intra_tubeo_db
    database_user: ajacss
    database_password: ckcsakrch2
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 2dc066da5a27773fea4a793dab5ee0a7
    database_path: null
